# This file is NOT used for deployment. See static.yml instead.
# This file is kept just for reference, but it is NOT active.

name: Reference Deploy Config (INACTIVE)

on:
  # This workflow won't run automatically
  workflow_dispatch:
    inputs:
      run_disabled_workflow:
        description: 'Confirm you want to run this INACTIVE workflow (not recommended)'
        required: true
        default: 'no'

permissions: {}

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Notice
        run: echo "This workflow is disabled. Use the static.yml workflow for GitHub Pages deployment instead."