name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          
      - name: Install and Build
        run: |
          npm install
          npm run build
          
          # If the client files are in dist/public
          if [ -d "dist/public" ]; then
            mkdir -p deploy
            cp -r dist/public/* deploy/
            cp deploy/index.html deploy/404.html
          # If the client files are in dist/client
          elif [ -d "dist/client" ]; then
            mkdir -p deploy
            cp -r dist/client/* deploy/
            cp deploy/index.html deploy/404.html
          # If the client files are directly in dist
          else
            mkdir -p deploy
            cp -r dist/* deploy/
            cp deploy/index.html deploy/404.html
          fi
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages