name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: npm install
      - name: Build for GitHub Pages
        run: |
          # Create a simple index.html for the client build
          cat > index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>Striktly - PEPPOL Invoice Management</title>
              <meta name="description" content="Striktly is a modern PEPPOL compliant invoice management platform designed to simplify business compliance and streamline international invoicing processes." />
            </head>
            <body>
              <div id="root"></div>
              <script type="module" src="/client/src/main.tsx"></script>
            </body>
          </html>
          EOL
          
          # Create a simple vite config for client-only build
          cat > vite.github.js << 'EOL'
          import { defineConfig } from "vite";
          import react from "@vitejs/plugin-react";
          import path from "path";
          
          export default defineConfig({
            plugins: [react()],
            base: "/StriktlyWebsiteNew/",
            build: {
              outDir: "./dist",
              emptyOutDir: true
            },
            resolve: {
              alias: {
                "@": path.resolve(__dirname, "./client/src"),
                "@assets": path.resolve(__dirname, "./attached_assets"),
                "@components": path.resolve(__dirname, "./client/src/components"),
                "@contexts": path.resolve(__dirname, "./client/src/contexts"),
                "@hooks": path.resolve(__dirname, "./client/src/hooks"),
                "@lib": path.resolve(__dirname, "./client/src/lib"),
                "@pages": path.resolve(__dirname, "./client/src/pages"),
                "@shared": path.resolve(__dirname, "./shared"),
                "@translations": path.resolve(__dirname, "./client/src/translations")
              }
            }
          });
          EOL
          
          # Build without the server
          npx vite build --config vite.github.js
          
          # Create 404.html for client-side routing
          cp dist/index.html dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1